### ISSUE TITLE
FlaME cannot currently open converted FlaME compatible formats.

### ISSUE THREAD

**Issue by Arithyce** [Mindstormsman/flaME#3]
Maps converted to the old FlaME compatible "bjo" and "lev" formats do not open in flame as they are not properly converted (for FlaME compatibility).

In the .lev file, the "game" field needs to have the full path to the .gam file, in the converted version it only has the filename of the .gam file. The proposed fix is to have flame be able to find the .gam file without the full path needing to be present.

It is possible to fix this in FlaME, since development has continued, so it may not need to be corrected in maptools. This will be posted as an issue in the maptools repo aswell.

**Comment by Mindstormsman** [comment]
Could you attach an example of one of these converted maps, I don't have or know how to use the maptools yet.

**Comment by Arithyce** [comment]
[2p-Arena_22.wz.zip](https://github.com/Mindstormsman/flaME/files/14323325/2p-Arena_22.wz.zip)
As for an example of a flame generated map, just throw one together real quick and compile.

**Comment by Arithyce** [comment]
This was fixed in 1.2.5 of maptools.
